lokalise/node-core

docs/ARRAY-UTILS.md
docs/OBJECT-UTILS.md
docs/README.md
index.ts
package.json
src/utils/__snapshots__/objectUtils.spec.ts.snap
src/utils/arrayUtils.spec.ts
src/utils/arrayUtils.ts
src/utils/objectUtils.spec.ts
src/utils/objectUtils.ts

Utils for working with arrays (chunking) and objects (copy, pick, groupBy, isEmptyObject).
Adopted wholesale from https://github.com/knex/knex-utils

Add array and object utils

---

package.json
src/http/httpClient.ts
src/utils/__snapshots__/objectUtils.spec.ts.snap
src/utils/objectUtils.spec.ts
src/utils/objectUtils.ts

Improved TS types for copyWithUndefined to properly return result without possible undefined values.

Fix TS compilation errors

---

.eslintrc.json
index.ts
package.json
src/http/httpClient.spec.ts
src/http/httpClient.ts
src/utils/objectUtils.ts

Keep-Alive header behaviour can be configured now.
Use smaller defaults to ensure we are below automatic AWS load balancer disconnects

Support configuring or disabling keep-alive

---

package.json
src/errors/either.ts
src/http/httpClient.spec.ts
src/http/httpClient.ts

This exposes HTTP client retry logic in an easy to consume format.

Support retry logic

---

docs/array-utils.md
src/utils/arrayUtils.spec.ts
src/utils/arrayUtils.ts

KRNL-221 add callChunked array function

---

src/config/ConfigScope.spec.ts
src/config/ConfigScope.ts

Given
```
VAR1=
VAR2=
```
and performing
```
var1: configScope.getOptionalInteger('VAR1', 42),
var2: configScope.getOptional('VAR2', 'foo'),
```
the produced configuration has inconsistent fallback behavior
```
{
var1: 42,
var2: '',
}
```
Use logical OR operator `||` instead of `??` in `ConfigScope.getOptional`.
Taking into account that `configScope.getOptional('VAR2', 'foo') currently returns an empty string, this change has the ability to break an application. 
Both for applications that rely on this behaviour and the ones that were not aware of this fallback behaviour.

Breaking change: Updated ConfigScope.getOptional to fallback to default value when environment variable is an empty string ('')

---

src/errors/InternalError.ts
src/errors/ResponseStatusError.ts

Make ResponseStatusError type more convenient to use via generic

Add generic to ResponseStatusError

---

src/errors/ResponseStatusError.ts
src/http/httpClient.spec.ts

Response is always available, so we can expose it more explicitly

Add type-safe access to response

---

package.json
src/config/ConfigScope.ts

This change improves the Type Guard quality of this function, typing end result as one of the passed values, and not just a generic "string" or "number"

Better narrowing down of types for getMandatoryOneOf

---

README.md
src/config/ConfigScope.spec.ts
src/config/ConfigScope.ts

Adding a new config method -> getOptionalOneOf

Config get optional one of

---

package.json

Bumping undici-retry to 2.0.1

---

src/http/httpClient.spec.ts
src/http/httpClient.ts

Add new method for sending binary with POST

Add sendPostBinary

---

src/config/ConfigScope.spec.ts
src/config/ConfigScope.ts

Treat empty string as a "null" value.

Empty string should count as null

---

src/errors/globalErrorHandler.ts

Use labels instead of numbers for log levels.

Use more standard log levels

---

docs/array-utils.md
index.ts
src/utils/arrayUtils.spec.ts
src/utils/arrayUtils.ts

Adding `removeNullish` and `removeFalsy` to facilitate array cleaning

Array remove nullish

---

docs/object-utils.md
index.ts
src/utils/objectUtils.spec.ts
src/utils/objectUtils.ts

Adding `convertDatesToIsoString` to transform an input object with `Date` members into an object with the corresponding `Date` members replaced by their ISO string representation. This transformation is done recursively, covering nested objects as well.

Convert date to string

---

docs/object-utils.md
src/utils/objectUtils.spec.ts
src/utils/objectUtils.ts

We were forcing to all props in `T` to be of type `string` `number` or `symbol`, where only `selector` one should have that type, so we allow to use the method with object with nested object, boolean properties or arrays

Group by bug fix

---

src/utils/typeUtils.ts

Previously incorrect type was established within isPublicNonRecoverableError typeguard

Fix PublicNonRecoverableError typeguard

---

package.json
src/http/httpClient.spec.ts
src/http/httpClient.ts

Now internal error are handled the same way as non-2xx block response errors, and are returned either as Either or thrown depending on the same config parameter.

Make error handling more consistent

---

index.ts

The new `success`, `failure`, `isSuccess`, `isFailure` helpers for the `Either` type were not being exported from the main index, and as such were inaccessible for consumers. This PR fixes that.

Export either helpers

---

index.ts
src/errors/ResponseStatusError.ts
src/errors/errorTypeGuards.spec.ts
src/errors/errorTypeGuards.ts

More robust way to check if error is an instance of ResponseStatusError

Add typeguard for ResponseStatusError

---

src/errors/InternalError.ts
src/errors/PublicNonRecoverableError.ts
src/errors/publicErrors.ts

This PR adds an optional passing of previous error as `cause` field (see https://nodejs.org/api/errors.html#errorcause) to allow to chain errors and keep original traces in case of re-wrapping.

Add passthrough of error.cause for PublicNonRecoverableError & InternalError

---

src/logging/commonLogger.ts

We rely on this method in bg-jobs-common lib, would be nice to have on a common interface.

Add isLevelEnabled to common logger interface

---

index.ts
src/errors/errorTypeGuards.spec.ts
src/errors/errorTypeGuards.ts
src/errors/publicErrors.ts

Adding entity gone error, useful to send back that the entity does no longer exists

Adding EntityGoneError

---

index.ts
package.json
src/utils/checksumUtils.spec.ts
src/utils/checksumUtils.ts
src/utils/streamUtils.spec.ts
src/utils/streamUtils.ts

Provides functions for persisting streams for multiple reuses in the future, and for the ease of the content-length calculation

Add functions for checksums and streams

---

src/config/configTypes.ts

In new services we want to start using `keyPrefix` instead of `db` for isolation.

MET-160 Add Redis keyPrefix to be used instead of db

---

package.json
src/observability/observabilityTypes.ts

For some transaction observability tools, might be beneficial to know if a transaction was successful or not, improving API to support it

Adding wasSuccessful param to TransactionObservabilityManager

---

package.json
src/config/configTypes.ts

Adding maxRetriesPerRequest parameter to RedisConfig, so that it can be used in default configuration object. 
See: https://lokalise.atlassian.net/browse/AP-5015

AP-5015 added maxRetriesPerRequest to RedisConfig

---

index.ts
package.json
src/errors/InternalError.spec.ts
src/errors/InternalError.ts
src/errors/PublicNonRecoverableError.spec.ts
src/errors/PublicNonRecoverableError.ts
src/errors/errorTypeGuards.ts
src/utils/typeUtils.spec.ts
src/utils/typeUtils.ts

adjust checking for internal and public errors

---

package.json
src/observability/MultiTransactionObservabilityManager.spec.ts
src/observability/MultiTransactionObservabilityManager.ts

Adding `MultiTransactionObservabilityManager` to facilitate grouping different managers

AP-5078 MultiTransactionObservabilityManager

---

index.ts

Exporting MultiTransactionObservabilityManager

---

package.json

Unpin @vitest/coverage-v8 and vitest from 2.0.5 specifically.

Unpin a specific version of @vitest/coverage-v8 and vitest

---

package.json

Sets the package entry point so it works well for CJS and ESM.

fix dual publish package entrypoint

---

src/errors/InternalError.spec.ts
src/errors/InternalError.ts
src/errors/PublicNonRecoverableError.spec.ts
src/errors/PublicNonRecoverableError.ts

This PR prevents the error symbol from being printed.
console.log output of the previous implementation:
console.log output of the new implementation

hide error symbol from being printed

---

README.md
src/config/ConfigScope.spec.ts
src/config/ConfigScope.ts

This PR adds float number validators to be available alongside integer ones.

Add float number config validators

---

README.md
src/config/ConfigScope.spec.ts
src/config/ConfigScope.ts

This PR adds `getBySchema` method that allows using zod schema to perform envvar validation.

add getBySchema method to configScope

---

src/index.ts
src/logging/stringValueSerializer.spec.ts
src/logging/stringValueSerializer.ts

Add JSON-based serializer that wraps values in quotes to prevent unwrapping by log collectors like Graylog

Add JSON-based log for serializing arbitrary values into an explicit string

---

src/config/ConfigScope.ts
src/errors/InternalError.ts
src/errors/PublicNonRecoverableError.ts
src/errors/publicErrors.ts
src/errors/types.ts

This reverts commit e1c6b52fc2622f956b7febd9092db87320046bb4.
This PR improves type-safety for InternalError details. The similar changes can be applied to PublicError once we agree on changes to Internal one.
Please take a look at the type-safety comparison below:
```
const a = new InternalError({ message: '', errorCode: '', details: { reason: '' } })
old: `details?: { reason: string } | undefined`
new: `details: { reason: string }`
const b = new InternalError({ message: '', errorCode: '' })
old: `details?: ErrorDetails | undefined`
new: `details: undefined`
const c = new InternalError<{ reason: string }>({ message: '', errorCode: '', details: { reason: '' } })
old: `details?: { reason: string } | undefined`
new: `details: { reason: string }`
const d = new InternalError<{ reason: string …
```

Reapply "feat: improve error details typesafety"

---

src/errors/InternalError.ts
src/errors/PublicNonRecoverableError.ts

The PR  allows to use `PublicNonRecoverableErrorParams` without passing a generic type. Like
```
type MyType = PublicNonRecoverableErrorParams & { extraParam: string }
```
Without this improvement we would have to specify it explicitly like
```
type MyType = PublicNonRecoverableErrorParams<undefined | ErrorDetails> & { extraParam: string }
```

chore: add default error param generic value
