lokalise/node-core

README.md
=> Update README to trigger release

.github/workflows/ci.yml
=> Run CI on Node 18 and 19

index.ts, package.json, src/http/httpClient.spec.ts, src/http/httpClient.ts
Support passing zod (or zod-like) schemas for typing and validating responses.
=> Implement response schema validation

index.ts, src/errors/ResponseStatusError.ts, src/http/httpClient.ts
Specific error for Response errors for easier parsing
=> Introduce ResponseStatusError

src/errors/ResponseStatusError.ts
=> Fix error name and types

package.json, src/utils/typeUtils.ts
Wrong field was check on StandardizedError
=> Fix error type check

src/utils/typeUtils.spec.ts, src/utils/typeUtils.ts
Use the real structure that e. g. fastify uses
=> Adjust type to correct value

src/config/configTypes.ts
Add TS types for redis timeout params
=> Add redis timeouts

src/config/ConfigScope.spec.ts, src/config/ConfigScope.ts
Add support for optionalNullableInteger config values
=> Implement optionalNullableInteger config

src/config/ConfigScope.ts, src/config/configTypes.ts
=> Fixes for redis config

index.ts, package.json, src/common/may-omit.ts, vitest.config.ts
=> Add MayOmit type

README.md, src/config/ConfigScope.spec.ts, src/config/ConfigScope.ts
Add new `ConfigScope.getOptionalValidatedInteger` method.
=> Add getOptionalValidatedInteger method

README.md, index.ts, src/utils/waitUtils.spec.ts, src/utils/waitUtils.ts
Test util for asynchronous flows
=> Implement waitAndRetry

src/errors/globalErrorHandler.ts
Log all errors that happen while executing a list of promises (useful for healthchecks)
=> Implement method for global logging of all settled promises with errors

index.ts
=> Add missing export

index.ts
=> Fix export for sendPostBinary

.eslintrc.json, README.md, package.json, src/errors/ResponseStatusError.ts, src/http/httpClient.spec.ts, src/http/httpClient.ts
Allows providing additional context for requests
=> Implement support for request labels

docs/object-utils.md, src/utils/objectUtils.spec.ts, src/utils/objectUtils.ts
Added a deepClone method for objects with tests and documentation.
=> AP-1334 Added deepClone method

index.ts
Added to export index.ts file.
=> Added deepClone into export

CODEOWNERS
=> Revise codeowners

README.md, package.json
=> Switch to undici 6

package.json, src/errors/globalErrorHandler.spec.ts, src/errors/globalErrorHandler.ts
Types became stricter in pino 8.17
=> Fix compatibility with new Pino version

src/http/httpClient.ts
Added JSON_HEADERS utility const to reuse it in http client calls.
=> Added JSON_HEADERS utility const.

index.ts
Forgot to export in main index.ts too.
=> Exposed JSON_HEADERS in index.ts

package.json
=> DXP-277 Add tslib dependency

index.ts, package.json, src/observability/observabilityTypes.ts
This provides common interface for different libraries and services providing or relying on background observability logic
=> Add type for observability manager

index.ts
=> Add missing export for DefiniteEither

README.md, index.ts, src/utils/ecnryptionUtility.spec.ts, src/utils/encryptionUtility.ts
Adapted encryption utility from https://github.com/MauriceButler/cryptr to TS.
=> AP-3599 Encryption utility based on Cryptr.

README.md, index.ts, src/utils/hashUtils.spec.ts, src/utils/hashUtils.ts
=> AP-3631 Add hash utils

package.json, src/errors/globalErrorHandler.spec.ts, src/errors/globalErrorHandler.ts
This ensure that we have more consistent log structure across the board
=> Make logging more consistent

package.json
=> Fixing lint issues on release action

docs/array-utils.md, src/utils/arrayUtils.spec.ts, src/utils/arrayUtils.ts
=> feat: add array util to remove duplicates

index.ts
=> add missing removeDuplicates export

src/index.ts
=> Missing transformToKebabCase export

package.json, src/config/ConfigScope.spec.ts
=> Support zod range

README.md, src/config/ConfigScope.spec.ts, src/config/ConfigScope.ts, src/errors/globalErrorHandler.ts, src/logging/loggerConfigResolver.spec.ts, src/logging/loggerConfigResolver.ts
Fixing missing zod import during migration
=> Bugfix: zod4 fix
